### ISSUE TITLE
Maliput road networks inspection

### ISSUE THREAD

**Issue by hidmic** [maliput/delphyne_gui#207]
## Description

Currently, our `maliput_viewer` can render Maliput road geometries for visual inspection. However, it does not provide similar capabilities for road network rule books.

This ticket tracks progress as `delphyne-gui`s capabilities are augmented to fill that gap.

## Stages

Work's split in two stages.

### 1. Consolidate inspection procedures

This stage serves two main purposes:

- To verify the practical usefulness of the inspection outcome and how it is presented (or even help defining how it should be presented).
- To implement the inspection logic itself, which is the same regardless of how I/O is handled.

To this end, the existing `malidrive_query` command line tool can be used as grounds to work on each POC.

#####  Tasks

- [x] Implement rules' (starting with right-of-way) inspection for a given lane region.
   - [x] https://github.com/ToyotaResearchInstitute/malidrive/pull/270
- [x] Implement rules' state and region of influence inspection for a given phase.
   - [x] https://github.com/ToyotaResearchInstitute/malidrive/pull/271

### 2. Support UI-based inspection

This stage deals with actually adding road network inspection support to `delphyne-gui`s visualizer. It does so incrementally, in two substages, using `ignition-gui`s plug-in widget infrastructure.

#### 2.1 Text-only I/O

The simplest transition from `malidrive_query` command line interface. This may include listing intersections, phases and/or rules in list or tree widgets, input boxes for region selection, dialogs, etc., suitable for each inspection procedure.

##### Tasks
- [ ] Show rules for a given lane.
   - [ ] https://github.com/ToyotaResearchInstitute/delphyne-gui/pull/221
- [ ] Filter rules for a given lane by phase.

#### 2.2 Graphical I/O

Once text I/O is in place, inspection support can be extended to provide graphical I/O as well. This may include include highlighting a rule's region of influence and/or providing visual cues for it [1], rendering traffic lights, rendering floating labels, supporting point-n-click lane and/or intersection selection [2], etc., suitable for each inspection procedure.

[1] Ignition rendering struggles somewhat with large road networks. Road overlays may be too high a burden for it. Road outlines may help use here, but we might hit a performance limitation.
[2] Click position-to-scene coordinates transformation appears to be non-trivial in `ignition-rendering` / `ogre`. To be confirmed.

##### Tasks

- [ ] Enable point-n-click selection for lanes
   - [x] https://github.com/ToyotaResearchInstitute/delphyne-gui/pull/217
   - [ ] https://github.com/ToyotaResearchInstitute/delphyne-gui/pull/221
- [ ] Implement a hovering/highlighting device for select lanes.
   - [ ] https://github.com/ToyotaResearchInstitute/delphyne-gui/pull/223
- [ ] Show `srh` and `xyz` coordinates for a clicked point.
- [ ] Add sliders for `s` lane region definition.
