### ISSUE TITLE
Unify visualizers

### ISSUE THREAD

**Issue by hidmic** [maliput/delphyne_gui#216]
## Description

Currently, we have two visualizer applications: one used as a simulation front-end (aka the `visualizer`) and another one used for static road visualization (aka the `maliput_viewer`). Both build on top of ignition libraries and their configurable plugin infrastructure. 

We'd want to unify both so as to have a single application that can be re-purposed via plugin (and thus layout) selection.

## Tasks

- [x] Encapsulate all `maliput_viewer` functionality into plugins (if not done yet).
- [x] Recreate `maliput_viewer` UI using a `visualizer` layout. 
- [x] Make `maliput_viewer` an alias to `visualizer` with the right configuration.
