### ISSUE TITLE
Meta ticket for various minor visualization issues

### ISSUE THREAD

**Issue by JShep1** [maliput/delphyne_gui#258]
- [ ] Key Consolidation - Seen in the key usage for the lane selection functionality, there is close relationship between the keys used for both mesh storage, and the key creation for mesh value location.  The three files which they are utilized in are `maliput_viewer_widget.hh/cc`, `layer_selection_widget.hh/cc`, and `generate_obj.hh/cc` within `maliput`.  These keys need to be consolidated and put in one location.
- [ ] Z Prioritization for Selected Lanes - Upon a lane being selected, if there happens to be an overlapping lane and the user clicks on the overlapping section, the lane that wasn't selected will be selected.  There needs to be a prioritization for the selected lane to be deselected when the user clicks an area in which the lanes overlap.
- [ ] Mesh Checkbox Inconsistency Upon Initialization - If the user clicks the mesh check boxes on the right hand side before loading a road geometry and then proceeds to load a road geometry, then the meshes will not be loaded in accordance with the check box values - they all will still load in as if they should all be visualized.  When the user proceeds to click around or toggle check boxes, the visualizer will behave correctly.  This isn't a super urgent task, but would fix a minor bug.

**Comment by francocipollone** [comment]
Closing as application changed a lot since this ticket was filled. See https://github.com/maliput/maliput_viz
