### ISSUE TITLE
Maliput viewer

### ISSUE THREAD

**Issue by basicNew** [maliput/delphyne_gui#35]
### Bare bones

- [x] Create an empty 3D widget that uses 100% of the window.
- [x] Add support for reading command line parameters. Read a path from the command line that should point to the maliput file.
- [x] Given a path, load the road geometry in memory (this will require using maliput as a library). Focus on multilane for a starter.
- [x] Write the code that takes a road network pointer and returns a set of named meshes / layers.
- [x] Populate the 3D scene with the meshes.

**Key Result:** demonstrate the viewer, loading from the command line, a Maliput multilane format.

### Information labels (see maliput/maliput_viz#14)

- [ ] Set labels with the IDs for all the entities and no toggling can be done.
- [x] Provide the control box with different check boxes.
- [ ] Modify label duplication if necessary.
- [ ] Usability improvements.

**Key Result:** load a multilane road network and properly visualize text labels with relevant IDs.

### RoadGeometry properties (see issue maliput/delphyne_gui#113)

- [ ] After a click in the 3D widget over a road, get the 3D world coordinate from it in a text field.
- [ ] After a click in the 3D widget over a road, properly visualize coordinates and road metadata (eg lane ID).

**Key Result:** load a maliput multilane road netowork and get relevant information (eg. world and lane coordinates) after clicking on the road network.

### Load from widget and enable rendering options

- [ ] Add a UI button that opens a file dialog to choose the file to load. (Needs review)
- [ ] Add a set of checkboxes to show/hide different features.
- [ ] Add a button that allows to reloading current loaded file. (Needs review)

**Key Result:** load a maliput multilane from the widget and enable/disable rendering of features

### Simulation Functionality

- [ ] Establish a connection with the backend to receive the road network from it.
- [ ] Enable loading/rendering of a road network given a specification passed from the simulator.

**Key Result:** view/introspect road networks passed from the simulator.
